(()=>{
  function addBirthdayField(){const modal=document.querySelector('#childModal .sheet');if(!modal||document.querySelector('#birthdayInput'))return;const photo=document.querySelector('#photoInput')?.closest('.field');const field=document.createElement('div');field.className='field';field.innerHTML='<label>Date de naissance 🎂</label><input id="birthdayInput" type="date">';photo?.after(field)}
  addBirthdayField();
  const b=()=>document.querySelector('#birthdayInput');
  const oldEdit=window.editChild;window.editChild=id=>{oldEdit?.(id);setTimeout(()=>{const c=state.children.find(x=>x.id===id);if(b())b().value=c?.birthday||''},0)};
  document.querySelector('#addChild')?.addEventListener('click',()=>setTimeout(()=>{if(b())b().value=''},0));
  document.querySelector('#saveChild')?.addEventListener('click',()=>{const val=b()?.value||'',id=typeof editId!=='undefined'?editId:null,name=document.querySelector('#nameInput')?.value.trim();setTimeout(()=>{let c=id?state.children.find(x=>x.id===id):[...state.children].reverse().find(x=>x.name===name);if(c){c.birthday=val;persist()}},50)});
  function genericBirthday(c){const o=document.createElement('div');o.style='position:fixed;inset:0;z-index:17000;background:rgba(25,45,70,.35);backdrop-filter:blur(7px);display:flex;align-items:center;justify-content:center;padding:18px';o.innerHTML=`<div style="background:white;border-radius:32px;padding:22px;text-align:center;box-shadow:0 30px 90px #0004;max-width:420px;width:92vw"><img src="${c.photo||avatar(c.name)}" style="width:220px;height:220px;object-fit:cover;border-radius:50%;border:6px solid white"><div style="font-size:54px;margin-top:-25px">🎉🎂🎈</div><div style="font-size:30px;font-weight:950;color:#17365d">Joyeux anniversaire ${c.name} !</div><div style="color:#718096;margin-top:6px">Une journée rien que pour toi 💕</div></div>`;document.body.appendChild(o);setTimeout(()=>o.remove(),3500)}
  function check(){const d=new Date(),md=`${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,key=`birthday-shown-${todayKey()}`;let shown=JSON.parse(localStorage.getItem(key)||'[]');state.children.forEach(c=>{if(!c.birthday||!c.present)return;if(c.birthday.slice(5)!==md||shown.includes(c.id))return;shown.push(c.id);localStorage.setItem(key,JSON.stringify(shown));setTimeout(()=>{if((c.name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()==='nora'&&window.NoraPack?.playBirthday)window.NoraPack.playBirthday();else genericBirthday(c)},700)})}
  setTimeout(check,1200);document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(check,400)});
})();