(()=>{
  const MEALS={tout:'Tout mangé',un_peu:'Un peu',rien:'Rien mangé',refuse:'Refusé'};
  const MOODS={joyeux:'Joyeux',calme:'Calme',fatigue:'Fatigué',grognon:'Grognon'};
  const now=()=>new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'});
  const care=(c,date=todayKey())=>{state.careRecords[date]=state.careRecords[date]||{};return state.careRecords[date][c.id]=state.careRecords[date][c.id]||{arrival:'',departure:'',meal:'',snack:'',bottle:'',napStart:'',napEnd:'',noNap:false,wet:0,stool:0,potty:0,mood:'',activity:'',note:''}};
  function ensure(){
    state.careRecords=state.careRecords||{};
    state.children.forEach(c=>{c.profile={contacts:'',pickups:'',allergies:'',foods:'',sleep:'',comfort:'',doctor:'',emergency:'',medical:'',prescription:'',photo:false,outings:false,...(c.profile||{})};c.reminders=Array.isArray(c.reminders)?c.reminders:[];c.memories=Array.isArray(c.memories)?c.memories:[];care(c)});
  }
  function completed(c,d=care(c)){return[d.arrival,d.meal,d.noNap||d.napStart,d.wet+d.stool+d.potty>0,d.departure].filter(Boolean).length}
  function missing(c,d=care(c)){return[['arrivée',d.arrival],['repas',d.meal],['sieste',d.noNap||d.napStart],['change',d.wet+d.stool+d.potty>0],['départ',d.departure]].filter(x=>!x[1]).map(x=>x[0])}
  function duration(d){if(!d.napStart||!d.napEnd)return'';const [a,b]=[d.napStart,d.napEnd].map(t=>{const [h,m]=t.split(':').map(Number);return h*60+m});let n=b-a;if(n<0)n+=1440;return`${Math.floor(n/60)} h ${String(n%60).padStart(2,'0')}`}
  function save(){ensure();localStorage.setItem(KEY,JSON.stringify(state));draw()}
  function inject(){
    const style=document.createElement('style');style.textContent=`
      .careDash{margin-top:16px;background:white;border-radius:24px;padding:16px;box-shadow:var(--shadow)}.careHead{display:flex;justify-content:space-between;align-items:center;gap:8px}.careHead h3{margin:0}.careActions{display:flex;gap:7px;overflow:auto;margin:12px 0}.careActions button,.careMini{border:0;border-radius:13px;padding:9px 11px;background:#edf4fa;color:var(--ink);font-weight:850;white-space:nowrap}.careRows{display:grid;gap:8px}.careRow{background:#f7f9fc;border-radius:17px;padding:11px}.careRowTop{display:flex;justify-content:space-between;align-items:center;gap:8px}.careProgress{height:7px;background:#e3eaf1;border-radius:9px;overflow:hidden;margin:7px 0}.careProgress i{display:block;height:100%;background:#45b883;border-radius:9px}.careMissing{color:#a05d33;font-size:11px}.careTags{display:flex;gap:5px;overflow:auto;margin-top:7px}.careTag{font-size:11px;background:white;border-radius:999px;padding:5px 7px;white-space:nowrap}.careRowBtns{display:flex;gap:5px;margin-top:8px}.careRowBtns button{flex:1;border:0;border-radius:11px;padding:8px 5px;background:white;color:var(--ink);font-weight:800}.careModal{position:fixed;inset:0;z-index:45000;background:#14263d70;display:none;align-items:flex-end;justify-content:center;padding:12px}.careModal.open{display:flex}.careSheet{background:white;color:#17365d;border-radius:26px 26px 18px 18px;padding:18px;width:min(100%,680px);max-height:90vh;overflow:auto}.careClose{border:0;border-radius:13px;padding:10px 14px;background:#eaf0f6;font-weight:850;float:right}.careSheet h2{margin:0 0 12px}.careGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.careField{display:grid;gap:5px;margin:8px 0}.careField label{font-size:12px;color:#728097}.careField input,.careField select,.careField textarea{width:100%;padding:10px;border:1px solid #d9e0e8;border-radius:12px;font:inherit}.careField textarea{min-height:68px;resize:vertical}.careCounters{display:flex;gap:7px}.careCounters button{flex:1;border:0;background:#edf4fa;border-radius:12px;padding:10px}.careNotice{background:#fff4d6;border-radius:14px;padding:10px;margin:9px 0}.careChecks{display:flex;gap:8px;flex-wrap:wrap}.careChecks label{background:#f3f6f9;border-radius:12px;padding:8px}.monthTable{width:100%;border-collapse:collapse;font-size:12px}.monthTable th,.monthTable td{padding:7px;border-bottom:1px solid #e6ebf0;text-align:center}.memory{background:#f6f8fb;border-radius:15px;padding:10px;margin:8px 0}.memory img{width:100%;max-height:220px;object-fit:cover;border-radius:12px;margin-top:7px}body[data-theme="night"] .careDash,body[data-theme="night"] .careRow{background:#24334a;color:#edf6ff}body[data-theme="night"] .careTag,body[data-theme="night"] .careRowBtns button{background:#1d2a3d;color:#edf6ff}@media(max-width:540px){.careGrid{grid-template-columns:1fr}.careHead{align-items:flex-start}.careRowBtns{overflow:auto}.careRowBtns button{min-width:92px}}
    `;document.head.appendChild(style);
    const dash=document.createElement('section');dash.className='careDash';dash.id='careDash';document.querySelector('#weekDash').after(dash);
    const modal=document.createElement('div');modal.id='careModal';modal.className='careModal';modal.innerHTML='<div class="careSheet"><button class="careClose" onclick="Care28.close()">Fermer</button><div id="careContent"></div></div>';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)close()});
  }
  function render(){
    ensure();const kids=state.children.filter(c=>c.present&&c.kind==='accueilli'),openCount=kids.reduce((n,c)=>n+missing(c).length,0);
    document.querySelector('#careDash').innerHTML=`<div class="careHead"><div><h3>🧸 Cahier de journée</h3><small>${kids.length?kids.length+' enfant'+(kids.length>1?'s':'')+' accueilli'+(kids.length>1?'s':'')+' présent'+(kids.length>1?'s':''):'Aucun enfant accueilli présent'}</small></div><b>${kids.length?(openCount?'🟠 '+openCount+' infos':'🟢 Complet'):''}</b></div><div class="careActions"><button onclick="Care28.group()" ${kids.length?'':'disabled'}>👨‍👩‍👧 Saisie groupée</button><button onclick="Care28.month()">🗓️ Mois</button></div><div class="careRows">${kids.map(c=>{const d=care(c),miss=missing(c),tags=[c.profile.allergies&&`⚠️ ${c.profile.allergies}`,c.reminders.length&&`🧺 ${c.reminders.join(', ')}`,d.arrival&&`↘ ${d.arrival}`,d.meal&&`🍽️ ${MEALS[d.meal]}`,d.napStart&&`😴 ${d.napStart}${d.napEnd?'–'+d.napEnd:''}`,d.noNap&&'😴 Pas de sieste',(d.wet+d.stool+d.potty)&&`🧷 ${d.wet+d.stool+d.potty}`,d.mood&&`🙂 ${MOODS[d.mood]}`].filter(Boolean);return`<div class="careRow"><div class="careRowTop"><b>${esc(c.name)}</b><span>${completed(c,d)}/5</span></div><div class="careProgress"><i style="width:${completed(c,d)*20}%"></i></div>${miss.length?`<div class="careMissing">À renseigner : ${miss.join(', ')}</div>`:'<div class="careMissing" style="color:#23845f">Journée complète ✓</div>'}<div class="careTags">${tags.map(t=>`<span class="careTag">${esc(t)}</span>`).join('')}</div><div class="careRowBtns"><button onclick="Care28.journal('${c.id}')">📝 Journée</button><button onclick="Care28.profile('${c.id}')">📌 Fiche</button><button onclick="Care28.memory('${c.id}')">📸 Souvenirs</button></div></div>`}).join('')}</div>`;
  }
  function open(html){document.querySelector('#careContent').innerHTML=html;document.querySelector('#careModal').classList.add('open')}
  function close(){document.querySelector('#careModal').classList.remove('open')}
  function child(id){return state.children.find(c=>c.id===id)}
  function journal(id){const c=child(id),d=care(c);open(`<h2>📝 Journée de ${esc(c.name)}</h2>${c.profile.allergies?`<div class="careNotice">⚠️ Allergies : <b>${esc(c.profile.allergies)}</b></div>`:''}<div class="careGrid"><div class="careField"><label>Arrivée</label><input id="cArrival" type="time" value="${d.arrival}"><button class="careMini" onclick="document.querySelector('#cArrival').value='${now()}'">Maintenant</button></div><div class="careField"><label>Départ</label><input id="cDeparture" type="time" value="${d.departure}"><button class="careMini" onclick="document.querySelector('#cDeparture').value='${now()}'">Maintenant</button></div><div class="careField"><label>Repas de midi</label><select id="cMeal"><option value="">Non renseigné</option>${Object.entries(MEALS).map(([v,l])=>`<option value="${v}" ${d.meal===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="careField"><label>Goûter</label><select id="cSnack"><option value="">Non renseigné</option>${Object.entries(MEALS).map(([v,l])=>`<option value="${v}" ${d.snack===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="careField"><label>Biberon / quantité</label><input id="cBottle" value="${esc(d.bottle)}" placeholder="ex. 180 ml"></div><div class="careField"><label>Humeur</label><select id="cMood"><option value="">Non renseignée</option>${Object.entries(MOODS).map(([v,l])=>`<option value="${v}" ${d.mood===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="careField"><label>Début de sieste</label><input id="cNapStart" type="time" value="${d.napStart}"></div><div class="careField"><label>Réveil ${duration(d)?'('+duration(d)+')':''}</label><input id="cNapEnd" type="time" value="${d.napEnd}"></div></div><label><input id="cNoNap" type="checkbox" ${d.noNap?'checked':''}> Pas de sieste aujourd’hui</label><div class="careField"><label>Changes</label><div class="careCounters"><button onclick="Care28.bump('${id}','wet')">💧 Pipi<br><b>${d.wet}</b></button><button onclick="Care28.bump('${id}','stool')">💩 Selle<br><b>${d.stool}</b></button><button onclick="Care28.bump('${id}','potty')">🚽 Pot<br><b>${d.potty}</b></button></div></div><div class="careField"><label>Activité</label><input id="cActivity" value="${esc(d.activity)}" placeholder="Peinture, promenade, lecture…"></div><div class="careField"><label>Petit mot</label><textarea id="cNote" placeholder="Une anecdote ou une information utile">${esc(d.note)}</textarea></div><button class="actionBtn" onclick="Care28.saveJournal('${id}')">Enregistrer la journée</button>`)}
  function readJournal(d){d.arrival=document.querySelector('#cArrival').value;d.departure=document.querySelector('#cDeparture').value;d.meal=document.querySelector('#cMeal').value;d.snack=document.querySelector('#cSnack').value;d.bottle=document.querySelector('#cBottle').value.trim();d.mood=document.querySelector('#cMood').value;d.napStart=document.querySelector('#cNapStart').value;d.napEnd=document.querySelector('#cNapEnd').value;d.noNap=document.querySelector('#cNoNap').checked;d.activity=document.querySelector('#cActivity').value.trim();d.note=document.querySelector('#cNote').value.trim()}
  function bump(id,key){const d=care(child(id));readJournal(d);d[key]=(d[key]||0)+1;save();journal(id)}
  function saveJournal(id){const d=care(child(id));readJournal(d);save();close()}
  function group(){const kids=state.children.filter(c=>c.present&&c.kind==='accueilli');open(`<h2>👨‍👩‍👧 Saisie groupée</h2><div class="careChecks">${kids.map(c=>`<label><input type="checkbox" class="groupKid" value="${c.id}" checked> ${esc(c.name)}</label>`).join('')}</div><div class="careField"><label>Information à ajouter</label><select id="groupAction"><option value="arrival">Arrivée maintenant</option><option value="meal">Repas : tout mangé</option><option value="snack">Goûter : tout mangé</option><option value="napStart">Début de sieste maintenant</option><option value="napEnd">Réveil maintenant</option><option value="wet">Change : pipi</option><option value="stool">Change : selle</option><option value="mood">Humeur : joyeux</option><option value="activity">Activité du jour</option></select></div><div class="careField"><label>Activité, si nécessaire</label><input id="groupText" placeholder="ex. promenade au parc"></div><button class="actionBtn" onclick="Care28.applyGroup()">Appliquer</button>`)}
  function applyGroup(){const ids=[...document.querySelectorAll('.groupKid:checked')].map(x=>x.value),action=document.querySelector('#groupAction').value,text=document.querySelector('#groupText').value.trim();ids.forEach(id=>{const d=care(child(id));if(action==='arrival'||action==='napStart'||action==='napEnd')d[action]=now();else if(action==='meal'||action==='snack')d[action]='tout';else if(action==='wet'||action==='stool')d[action]=(d[action]||0)+1;else if(action==='mood')d.mood='joyeux';else if(action==='activity'&&text)d.activity=text});save();close()}
  function profile(id){const c=child(id),p=c.profile;open(`<h2>📌 Fiche de ${esc(c.name)}</h2><p>Ces informations restent enregistrées sur cet appareil.</p>${[['Contacts des parents','pContacts',p.contacts,'Téléphones et noms'],['Personnes autorisées','pPickups',p.pickups,'Personnes autorisées à venir chercher l’enfant'],['Allergies','pAllergies',p.allergies,'À afficher en priorité'],['Aliments interdits','pFoods',p.foods,''],['Habitudes de sommeil','pSleep',p.sleep,''],['Doudou et tétine','pComfort',p.comfort,''],['Médecin','pDoctor',p.doctor,'Nom et téléphone'],['Contact d’urgence','pEmergency',p.emergency,''],['Informations médicales','pMedical',p.medical,'PAI, traitement, consignes…'],['Ordonnance valable jusqu’au','pPrescription',p.prescription,'JJ/MM/AAAA']].map(([l,i,v,ph])=>`<div class="careField"><label>${l}</label><input id="${i}" value="${esc(v)}" placeholder="${ph}"></div>`).join('')}<div class="careChecks"><label><input id="pPhoto" type="checkbox" ${p.photo?'checked':''}> Photos autorisées</label><label><input id="pOutings" type="checkbox" ${p.outings?'checked':''}> Sorties autorisées</label></div><div class="careField"><label>Rappels aux parents, séparés par une virgule</label><input id="pReminders" value="${esc(c.reminders.join(', '))}" placeholder="Couches, lingettes, vêtements…"></div><button class="actionBtn" onclick="Care28.saveProfile('${id}')">Enregistrer la fiche</button>`)}
  function saveProfile(id){const c=child(id),p=c.profile,map={contacts:'pContacts',pickups:'pPickups',allergies:'pAllergies',foods:'pFoods',sleep:'pSleep',comfort:'pComfort',doctor:'pDoctor',emergency:'pEmergency',medical:'pMedical',prescription:'pPrescription'};Object.entries(map).forEach(([k,i])=>p[k]=document.querySelector('#'+i).value.trim());p.photo=document.querySelector('#pPhoto').checked;p.outings=document.querySelector('#pOutings').checked;c.reminders=document.querySelector('#pReminders').value.split(',').map(x=>x.trim()).filter(Boolean);save();close()}
  function memory(id){const c=child(id);open(`<h2>📸 Souvenirs de ${esc(c.name)}</h2><div class="careField"><label>Nouveau souvenir</label><input id="memoryText" placeholder="Premier dessin, nouveau mot…"><input id="memoryPhoto" type="file" accept="image/*"></div><button class="actionBtn" onclick="Care28.addMemory('${id}')">Ajouter</button><div>${c.memories.slice().reverse().map(m=>`<div class="memory"><b>${new Date(m.date+'T12:00:00').toLocaleDateString('fr-FR')}</b><div>${esc(m.text)}</div>${m.photo?`<img src="${m.photo}" alt="Souvenir">`:''}</div>`).join('')||'<p>Aucun souvenir enregistré.</p>'}</div>`)}
  async function compressed(file){if(!file)return'';const url=URL.createObjectURL(file),img=new Image;await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url});const scale=Math.min(1,900/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);return canvas.toDataURL('image/jpeg',.72)}
  async function addMemory(id){const text=document.querySelector('#memoryText').value.trim(),file=document.querySelector('#memoryPhoto').files[0];if(!text&&!file)return alert('Ajoute un petit texte ou une photo.');try{child(id).memories.push({date:todayKey(),text,photo:await compressed(file)});save();memory(id)}catch{alert('Cette photo n’a pas pu être enregistrée.')}}
  function month(){const dates=Object.keys(state.careRecords).sort().slice(-31),kids=state.children.filter(c=>c.kind==='accueilli');open(`<h2>🗓️ Présences du mois</h2><div style="overflow:auto"><table class="monthTable"><thead><tr><th>Date</th>${kids.map(c=>`<th>${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${dates.map(date=>`<tr><td>${new Date(date+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'})}</td>${kids.map(c=>{const d=state.careRecords[date]?.[c.id];return`<td>${d?.arrival?`${d.arrival}${d.departure?'–'+d.departure:''}`:'—'}</td>`}).join('')}</tr>`).join('')}</tbody></table></div><button class="actionBtn" onclick="Care28.exportMonth()">Exporter le relevé</button>`)}
  function exportMonth(){const kids=state.children.filter(c=>c.kind==='accueilli'),dates=Object.keys(state.careRecords).sort().slice(-31),rows=[['Date',...kids.map(c=>c.name)],...dates.map(date=>[date,...kids.map(c=>{const d=state.careRecords[date]?.[c.id];return d?.arrival?`${d.arrival}-${d.departure||''}`:''})])],csv=rows.map(r=>r.map(x=>'"'+String(x).replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`presences-${todayKey()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function summaryText(c){const d=care(c),line=(label,value)=>value?`\n${label} : ${value}`:'';return`Bilan de ${c.name} — ${new Date().toLocaleDateString('fr-FR')}\nPrésence : ${c.present?'oui':'non'}${line('Accueil',[d.arrival,d.departure].filter(Boolean).join(' – '))}${line('Repas',MEALS[d.meal])}${line('Goûter',MEALS[d.snack])}${line('Biberon',d.bottle)}${line('Sieste',d.noNap?'pas de sieste':[d.napStart,d.napEnd].filter(Boolean).join(' – ')+(duration(d)?` (${duration(d)})`:''))}${line('Changes',`${d.wet} pipi, ${d.stool} selle, ${d.potty} pot`)}${line('Humeur',MOODS[d.mood])}${line('Activité',d.activity)}${line('Petit mot',d.note)}\nBêtises : ${c.kind==='accueilli'?fmt(c.midi):`midi ${fmt(c.midi)} / soir ${fmt(c.soir)}`}\nBonnes actions : ${c.stars} ⭐${c.goal?`\nObjectif : ${c.goal}`:''}${c.reminders.length?`\nÀ prévoir : ${c.reminders.join(', ')}`:''}\n${status(c)}`}
  function summary(id=state.children[0]?.id){const c=child(id)||state.children[0],options=state.children.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${esc(x.name)}</option>`).join('');document.querySelector('#v27content').innerHTML=`<h2>💌 Bilan du jour</h2><select class="v27select" onchange="V27.summary(this.value)">${options}</select><div class="summaryBox" id="parentSummary">${esc(summaryText(c))}</div><button class="actionBtn" onclick="V27.copySummary()">Copier</button><button class="actionBtn" onclick="V27.shareSummary()">Partager</button>`;document.querySelector('#v27modal').classList.add('open')}
  ensure();inject();const persistBefore=persist;persist=function(redraw=true){ensure();return persistBefore(redraw)};const drawBefore=draw;draw=function(){drawBefore();render()};V27.summary=summary;window.Care28={close,journal,bump,saveJournal,group,applyGroup,profile,saveProfile,memory,addMemory,month,exportMonth};save();
})();
