(()=>{
  const SPRITE_RAW='https://raw.githubusercontent.com/ecopilot-project/Petites-b-tises/main/Asset/Nora/nora-sprite.WEBP';
  const SPRITE_LOCAL='./Asset/Nora/nora-sprite.WEBP';
  const frameIndex={zero:0,half:1,one:2,two:3,three:4,good:5,birthday:6};
  const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const isNora=c=>norm(c?.name)==='nora';
  let spritePromise=null,overlay=null;
  function loadSprite(){if(spritePromise)return spritePromise;spritePromise=new Promise((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=()=>{const j=new Image();j.onload=()=>resolve(j);j.onerror=reject;j.src=SPRITE_LOCAL+'?v=2'};i.src=SPRITE_RAW+'?v=2'});return spritePromise}
  function ensureOverlay(){if(overlay)return overlay;overlay=document.createElement('div');overlay.id='noraPackOverlay';overlay.innerHTML=`<style>#noraPackOverlay{position:fixed;inset:0;display:none;align-items:center;justify-content:center;z-index:16000;background:rgba(24,42,66,.38);backdrop-filter:blur(7px);padding:18px}#noraPackOverlay.show{display:flex}#noraPackCard{width:min(92vw,430px);background:#fff;border-radius:34px;padding:16px;box-shadow:0 30px 90px rgba(0,0,0,.28);text-align:center;animation:noraIn .25s ease-out}#noraCanvas{width:100%;aspect-ratio:1;border-radius:26px;display:block;background:#f3f6fa}#noraTitle{font-size:31px;line-height:1.05;font-weight:950;color:#17365d;margin-top:12px}#noraSub{font-size:16px;color:#718096;margin-top:5px}@keyframes noraIn{from{transform:scale(.82);opacity:0}to{transform:scale(1);opacity:1}}</style><div id="noraPackCard"><canvas id="noraCanvas" width="320" height="320"></canvas><div id="noraTitle"></div><div id="noraSub"></div></div>`;document.body.appendChild(overlay);return overlay}
  function stateFor(total){if(total>=3)return'three';if(total>=2)return'two';if(total>=1)return'one';if(total>=.5)return'half';return'zero'}
  function drawFrame(ctx,img,state,alpha=1,scale=1){const idx=frameIndex[state],sx=idx*320;ctx.save();ctx.globalAlpha=alpha;ctx.translate(160,160);ctx.scale(scale,scale);ctx.drawImage(img,sx,0,320,320,-160,-160,320,320);ctx.restore()}
  function confetti(ctx,t){const cols=['#ff74a5','#ffd866','#72cfff','#80ddb0','#bc93ff'];for(let i=0;i<14;i++){const x=(i*47+30)%320,y=((t*430+i*37)%390)-40;ctx.fillStyle=cols[i%cols.length];ctx.beginPath();ctx.arc(x,y,3+(i%3),0,Math.PI*2);ctx.fill()}}
  async function play(fromState,toState,title,sub,celebrate=false,duration=1900){const img=await loadSprite(),o=ensureOverlay(),c=o.querySelector('#noraCanvas'),ctx=c.getContext('2d');o.querySelector('#noraTitle').textContent=title;o.querySelector('#noraSub').textContent=sub||'';o.classList.add('show');const start=performance.now();return new Promise(resolve=>{function tick(now){const t=Math.min(1,(now-start)/duration),s=t*t*(3-2*t);ctx.clearRect(0,0,320,320);drawFrame(ctx,img,fromState,1-s,1+.018*Math.sin(Math.PI*t));drawFrame(ctx,img,toState,s,1+.025*Math.sin(Math.PI*t));if(celebrate)confetti(ctx,t);if(t<1)requestAnimationFrame(tick);else setTimeout(()=>{o.classList.remove('show');resolve()},250)}requestAnimationFrame(tick)})}
  window.NoraPack={playBirthday:()=>play('zero','birthday','Joyeux anniversaire Nora ! 🎂','Une journée rien que pour toi 🎉',true,3000)};
  const prevBad=window.bad,prevGood=window.good;
  window.bad=(id,p,amount=1)=>{const c=state.children.find(x=>x.id===id);if(!c||!isNora(c))return prevBad?.(id,p,amount);const before=c[p]||0,from=stateFor(before);c.last.push(snapshot(c));c[p]=Math.min(state.settings.threshold,before+amount);addHistory(`${c.name} : +${amount===.5?'½':'1'} bêtise (${p})`);persist();const total=c[p],to=stateFor(total);let title=amount===.5?'Petit oups ! 😯':'Oups !',sub=`Nora : ${fmt(total)} / ${state.settings.threshold} (${p==='midi'?'midi':'soir'})`;if(total>=3){title='Oh oh… 😈';sub=`3 bêtises : pas de ${state.settings.reward}`}else if(total>=2){title='Attention… 😠';sub=`${fmt(total)} / ${state.settings.threshold} — plus qu’une !`}play(from,to,title,sub,false,2000).catch(()=>{})};
  window.good=id=>{const c=state.children.find(x=>x.id===id);if(!c||!isNora(c))return prevGood?.(id);c.last.push(snapshot(c));c.stars++;addHistory(`${c.name} : ⭐ bonne action`);persist();play(stateFor(Math.max(c.midi,c.soir)),'good','Bravo Nora ! ⭐','Super bonne action',true,2200).catch(()=>{})};
  setTimeout(()=>loadSprite().catch(()=>{}),500);
})();