(()=>{
 const PHOTO='https://raw.githubusercontent.com/ecopilot-project/Petites-b-tises/main/nora-photo-originale.webp';
 const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(),isNora=c=>norm(c?.name)==='nora';let overlay,imgPromise;
 function load(){return imgPromise||(imgPromise=new Promise((ok,no)=>{const i=new Image();i.onload=async()=>{try{await i.decode?.()}catch{}ok(i)};i.onerror=no;i.src=PHOTO+'?v=5'}))}
 function ui(){if(overlay)return overlay;const wrap=document.createElement('div');wrap.innerHTML=`<style>#nv5{position:fixed;inset:0;z-index:19000;display:none;align-items:center;justify-content:center;background:rgba(15,23,42,.44);padding:18px}#nv5.on{display:flex}#nv5c{width:min(92vw,430px);background:#fff;border-radius:34px;padding:14px;text-align:center;box-shadow:0 28px 80px rgba(0,0,0,.26)}#nv5stage{position:relative;overflow:hidden;border-radius:27px;aspect-ratio:1;background:#111827}#nv5img{width:100%;height:100%;object-fit:cover;opacity:1;display:block;will-change:transform}#nv5fx{position:absolute;inset:0;pointer-events:none}#nv5title{font:900 31px/1.05 system-ui;color:#17365d;margin:12px 0 4px}#nv5sub{font:500 16px system-ui;color:#718096}.bubble{position:absolute;right:5%;top:6%;background:#fff;border:4px solid #ff79a8;border-radius:24px;padding:9px 14px;font:900 21px system-ui;color:#c43b72;transform:translateY(-12px) scale(.7);opacity:0;transition:.42s cubic-bezier(.2,.9,.2,1.2)}.bubble.show{transform:translateY(0) scale(1);opacity:1}.fx{position:absolute;opacity:0;transform:scale(.5);transition:.45s cubic-bezier(.2,.9,.2,1.2)}.fx.show{opacity:1;transform:scale(1)}@keyframes gentleZoom{0%{transform:scale(1)}45%{transform:scale(1.045) translateY(-2px)}100%{transform:scale(1.02)}}@keyframes softNod{0%{transform:scale(1.01) translateY(0)}50%{transform:scale(1.035) translateY(3px)}100%{transform:scale(1.02) translateY(0)}}@keyframes warn{0%{transform:scale(1.01) rotate(0)}35%{transform:scale(1.045) rotate(-.45deg)}70%{transform:scale(1.045) rotate(.45deg)}100%{transform:scale(1.02) rotate(0)}}@keyframes bounce{0%,100%{transform:scale(1.01)}50%{transform:scale(1.05) translateY(-3px)}}</style><div id="nv5"><div id="nv5c"><div id="nv5stage"><img id="nv5img"><div id="nv5fx"></div></div><div id="nv5title"></div><div id="nv5sub"></div></div></div>`;document.body.appendChild(wrap.firstElementChild);overlay=document.querySelector('#nv5');return overlay}
 async function play(kind,title,sub){const pre=await load(),o=ui(),im=o.querySelector('#nv5img'),fx=o.querySelector('#nv5fx');im.style.animation='none';fx.innerHTML='';o.querySelector('#nv5title').textContent=title;o.querySelector('#nv5sub').textContent=sub;im.src=pre.src;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));o.classList.add('on');
   requestAnimationFrame(()=>{if(kind==='half'){im.style.animation='gentleZoom 1.55s ease-out forwards';fx.innerHTML='<div class="bubble">Oups ! 😯</div>';setTimeout(()=>fx.querySelector('.bubble')?.classList.add('show'),220)}
   else if(kind==='one'){im.style.animation='softNod 1.5s ease-in-out forwards';fx.innerHTML='<div class="bubble">Oh là là…</div>';setTimeout(()=>fx.querySelector('.bubble')?.classList.add('show'),250)}
   else if(kind==='two'){im.style.animation='warn 1.45s ease-in-out forwards';fx.innerHTML='<span class="fx" style="left:8%;top:14%;font-size:42px">⚡</span><span class="fx" style="right:8%;top:18%;font-size:42px">⚡</span><div class="bubble">Attention ! 😠</div>';setTimeout(()=>fx.querySelectorAll('.fx,.bubble').forEach(x=>x.classList.add('show')),220)}
   else if(kind==='three'){im.style.animation='warn 1.35s ease-in-out forwards';fx.innerHTML='<span class="fx" style="left:13%;top:2%;font-size:72px">🔺</span><span class="fx" style="right:13%;top:2%;font-size:72px">🔺</span><div class="bubble">3 bêtises ! 😈</div>';setTimeout(()=>fx.querySelectorAll('.fx,.bubble').forEach(x=>x.classList.add('show')),180)}
   else if(kind==='good'){im.style.animation='bounce 1.5s ease-in-out forwards';fx.innerHTML='<span class="fx" style="left:8%;top:15%;font-size:42px">⭐</span><span class="fx" style="right:10%;top:12%;font-size:42px">✨</span><div class="bubble">Bravo ! 💕</div>';setTimeout(()=>fx.querySelectorAll('.fx,.bubble').forEach(x=>x.classList.add('show')),180)}
   else if(kind==='birthday'){im.style.animation='bounce 1.8s ease-in-out forwards';fx.innerHTML='<span class="fx" style="left:8%;top:18%;font-size:44px">🎉</span><span class="fx" style="right:8%;top:18%;font-size:44px">🎈</span><div class="bubble">Joyeux anniversaire ! 🎂</div>';setTimeout(()=>fx.querySelectorAll('.fx,.bubble').forEach(x=>x.classList.add('show')),180)}});setTimeout(()=>o.classList.remove('on'),kind==='birthday'?3200:2200)}
 window.NoraPack={playBirthday:()=>play('birthday','Joyeux anniversaire Nora ! 🎂','Une journée rien que pour toi 🎉')};const pb=window.bad,pg=window.good;
 window.bad=(id,p,a=1)=>{const c=state.children.find(x=>x.id===id);if(!c||!isNora(c))return pb?.(id,p,a);c.last.push(snapshot(c));c[p]=Math.min(state.settings.threshold,(c[p]||0)+a);addHistory(`${c.name} : +${a===.5?'½':'1'} bêtise (${p})`);persist();const n=c[p],k=n>=3?'three':n>=2?'two':n>=1?'one':'half';play(k,n>=3?'Oh oh… 😈':n>=2?'Attention… 😠':a===.5?'Petit oups ! 😯':'Oups !',`${c.name} : ${fmt(n)} / ${state.settings.threshold} (${p==='midi'?'midi':'soir'})`).catch(()=>{})};
 window.good=id=>{const c=state.children.find(x=>x.id===id);if(!c||!isNora(c))return pg?.(id);c.last.push(snapshot(c));c.stars++;addHistory(`${c.name} : ⭐ bonne action`);persist();play('good','Bravo Nora ! ⭐','Super bonne action').catch(()=>{})};setTimeout(()=>load().catch(()=>{}),250);
})();