(()=>{
  const ROMANE_BASE='https://raw.githubusercontent.com/ecopilot-project/Petites-b-tises/main/Asset/Romane/';
  const NORA_PHOTO='./nora-photo-originale.webp';
  const files={zero:'zero.webp',half:'half.webp',one:'one.webp',two:'two.webp',three:'three.webp',good:'good.webp'};
  const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const who=c=>norm(c?.name);
  let overlay=null;
  function ensureOverlay(){if(overlay)return overlay;overlay=document.createElement('div');overlay.id='kidPackOverlay';overlay.innerHTML=`<style>#kidPackOverlay{position:fixed;inset:0;display:none;align-items:center;justify-content:center;z-index:25000;background:rgba(24,42,66,.45);padding:18px}#kidPackOverlay.show{display:flex}#kidPackCard{width:min(92vw,430px);background:white;border-radius:34px;padding:16px;box-shadow:0 30px 90px rgba(0,0,0,.28);text-align:center;animation:kpIn .28s cubic-bezier(.2,.9,.2,1.1)}#kidPackStage{position:relative;width:100%;aspect-ratio:1;overflow:hidden;border-radius:26px;background:#eef2f7}#kidPackImg{width:100%;height:100%;object-fit:cover;display:block}#kidPackFx{position:absolute;inset:0;pointer-events:none}.kpTag{position:absolute;left:50%;bottom:5%;transform:translate(-50%,25px) scale(.85);opacity:0;background:rgba(255,255,255,.95);border-radius:999px;padding:10px 16px;font:900 21px system-ui;color:#17365d;transition:.38s cubic-bezier(.2,1,.2,1.2)}.kpTag.on{transform:translate(-50%,0) scale(1);opacity:1}.kpEmoji{position:absolute;opacity:0;animation:kpPop .55s cubic-bezier(.2,1,.2,1.2) forwards}#kidPackTitle{font-size:31px;line-height:1.05;font-weight:950;color:#17365d;margin-top:12px}#kidPackSub{font-size:16px;color:#718096;margin-top:5px}@keyframes kpIn{from{transform:scale(.78);opacity:0}to{transform:scale(1);opacity:1}}@keyframes kpZoom{0%{transform:scale(1.02)}50%{transform:scale(1.07) translateY(-3px)}100%{transform:scale(1.04)}}@keyframes kpWarn{0%{transform:scale(1.02)}35%{transform:scale(1.065) rotate(-.4deg)}70%{transform:scale(1.065) rotate(.4deg)}100%{transform:scale(1.04)}}@keyframes kpPop{0%{opacity:0;transform:scale(.2) translateY(-25px)}70%{opacity:1;transform:scale(1.18)}100%{opacity:1;transform:scale(1)}}@keyframes kpFloat{0%{opacity:0;transform:translateY(25px) rotate(0)}20%{opacity:1}100%{opacity:0;transform:translateY(-230px) rotate(250deg)}}</style><div id="kidPackCard"><div id="kidPackStage"><img id="kidPackImg"><div id="kidPackFx"></div></div><div id="kidPackTitle"></div><div id="kidPackSub"></div></div>`;document.body.appendChild(overlay);return overlay}
  function pickState(total){if(total>=3)return'three';if(total>=2)return'two';if(total>=1)return'one';if(total>=.5)return'half';return'zero'}
  function particles(fx,chars,count=18){for(let i=0;i<count;i++){const s=document.createElement('span');s.textContent=chars[i%chars.length];s.style=`position:absolute;left:${4+Math.random()*90}%;bottom:${-5+Math.random()*20}%;font-size:${22+Math.random()*12}px;animation:kpFloat ${1.1+Math.random()*.6}s ease-out ${Math.random()*.35}s forwards`;fx.appendChild(s)}}
  async function playRomane(stateName,title,sub){const o=ensureOverlay(),img=o.querySelector('#kidPackImg'),fx=o.querySelector('#kidPackFx');fx.innerHTML='';img.style.animation='none';o.querySelector('#kidPackTitle').textContent=title;o.querySelector('#kidPackSub').textContent=sub||'';img.src=ROMANE_BASE+files[stateName]+'?v=17';o.classList.add('show');await new Promise(r=>setTimeout(r,stateName==='three'?2300:1900));o.classList.remove('show')}
  async function playNora(kind,title,sub){const o=ensureOverlay(),img=o.querySelector('#kidPackImg'),fx=o.querySelector('#kidPackFx');o.querySelector('#kidPackTitle').textContent=title;o.querySelector('#kidPackSub').textContent=sub||'';fx.innerHTML='';img.style.animation='none';img.src=NORA_PHOTO+'?v=17';o.classList.add('show');requestAnimationFrame(()=>{img.style.animation=(kind==='two'||kind==='three')?'kpWarn 1.6s ease-in-out forwards':'kpZoom 1.7s ease-out forwards';let tag='';if(kind==='half')tag='Petit oups ! 😯';if(kind==='one')tag='Oh là là… 😬';if(kind==='two')tag='Attention… plus qu’une !';if(kind==='three')tag='Pas de bonbon 😈';if(kind==='good')tag='Bravo Nora ! ⭐';if(kind==='birthday')tag='Joyeux anniversaire Nora ! 🎂';fx.innerHTML=`<div class="kpTag">${tag}</div>`;setTimeout(()=>fx.querySelector('.kpTag')?.classList.add('on'),120);if(kind==='half')fx.insertAdjacentHTML('beforeend','<span class="kpEmoji" style="right:8%;top:8%;font-size:58px">❗</span>');if(kind==='one')fx.insertAdjacentHTML('beforeend','<span class="kpEmoji" style="left:8%;top:10%;font-size:56px">💭</span>');if(kind==='two')fx.insertAdjacentHTML('beforeend','<span class="kpEmoji" style="left:8%;top:12%;font-size:58px">⚡</span><span class="kpEmoji" style="right:8%;top:15%;font-size:58px">⚡</span>');if(kind==='three')fx.insertAdjacentHTML('beforeend','<span class="kpEmoji" style="left:14%;top:2%;font-size:70px">🔺</span><span class="kpEmoji" style="right:14%;top:2%;font-size:70px">🔺</span>');if(kind==='good')particles(fx,['⭐','✨','💛'],24);if(kind==='birthday')particles(fx,['🎉','🎈','✨','💗'],30)});await new Promise(r=>setTimeout(r,kind==='birthday'?3300:2400));o.classList.remove('show')}
  window.NoraPack={playBirthday:()=>playNora('birthday','Joyeux anniversaire Nora ! 🎂','Aujourd’hui, c’est ta journée 🎉')};
  const previousBad=window.bad,previousGood=window.good;
  window.bad=(id,p,amount=1)=>{const c=state.children.find(x=>x.id===id);if(!c)return previousBad?.(id,p,amount);const n=who(c);if(n!=='romane'&&n!=='nora')return previousBad?.(id,p,amount);c.last.push(snapshot(c));c[p]=Math.min(state.settings.threshold,c[p]+amount);addHistory(`${c.name} : +${amount===.5?'½':'1'} bêtise (${p})`);persist();const total=c[p],st=pickState(total);let title=amount===.5?'Petit oups ! 😯':'Oups !',sub=`${c.name} : ${fmt(total)} / ${state.settings.threshold} (${p==='midi'?'midi':'soir'})`;if(total>=3){title='Oh oh… 😈';sub=`3 bêtises : pas de ${state.settings.reward}`}else if(total>=2){title='Attention… 😠';sub=`${fmt(total)} / ${state.settings.threshold} — plus qu’une !`}if(n==='romane')playRomane(st,title,sub).catch(()=>{});else playNora(st,title,sub).catch(()=>{})};
  window.good=id=>{const c=state.children.find(x=>x.id===id);if(!c)return previousGood?.(id);const n=who(c);if(n!=='romane'&&n!=='nora')return previousGood?.(id);c.last.push(snapshot(c));c.stars++;addHistory(`${c.name} : ⭐ bonne action`);persist();if(n==='romane')playRomane('good','Bravo Romane ! ⭐','Super bonne action').catch(()=>{});else playNora('good','Bravo Nora ! ⭐','Super bonne action').catch(()=>{})};
  Object.values(files).forEach(f=>{const i=new Image();i.src=ROMANE_BASE+f+'?v=17'});const n=new Image();n.src=NORA_PHOTO+'?v=17';
})();