(()=>{
  const ASSET_BASE='./Asset/Romane/';
  const files={zero:'zero.webp',half:'half.webp',one:'one.webp',two:'two.webp',three:'three.webp',good:'good.webp'};
  const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const isRomane=c=>norm(c?.name)==='romane';
  let overlay=null;
  function ensureOverlay(){if(overlay)return overlay;overlay=document.createElement('div');overlay.id='romanePackOverlay';overlay.innerHTML=`<style>#romanePackOverlay{position:fixed;inset:0;display:none;align-items:center;justify-content:center;z-index:15000;background:rgba(24,42,66,.38);backdrop-filter:blur(7px);padding:18px}#romanePackOverlay.show{display:flex}#romanePackCard{width:min(92vw,430px);background:white;border-radius:34px;padding:16px;box-shadow:0 30px 90px rgba(0,0,0,.28);text-align:center;animation:rpIn .28s cubic-bezier(.2,.9,.2,1.1)}#romanePackImg{width:100%;aspect-ratio:1;object-fit:cover;border-radius:26px;display:block;background:#f1f5f9}#romanePackTitle{font-size:31px;line-height:1.05;font-weight:950;color:#17365d;margin-top:12px}#romanePackSub{font-size:16px;color:#718096;margin-top:5px}@keyframes rpIn{from{transform:scale(.78);opacity:0}to{transform:scale(1);opacity:1}}</style><div id="romanePackCard"><img id="romanePackImg" alt="Animation de Romane"><div id="romanePackTitle"></div><div id="romanePackSub"></div></div>`;document.body.appendChild(overlay);return overlay}
  function pickState(total){if(total>=3)return'three';if(total>=2)return'two';if(total>=1)return'one';if(total>=.5)return'half';return'zero'}
  async function play(stateName,title,sub){const o=ensureOverlay(),img=o.querySelector('#romanePackImg');o.querySelector('#romanePackTitle').textContent=title;o.querySelector('#romanePackSub').textContent=sub||'';img.src=ASSET_BASE+files[stateName]+'?v=2';o.classList.add('show');await new Promise(r=>setTimeout(r,stateName==='three'?2300:1900));o.classList.remove('show')}
  const previousBad=window.bad,previousGood=window.good;
  window.bad=(id,p,amount=1)=>{const c=state.children.find(x=>x.id===id);if(!c||!isRomane(c))return previousBad?.(id,p,amount);c.last.push(snapshot(c));c[p]=Math.min(state.settings.threshold,c[p]+amount);addHistory(`${c.name} : +${amount===.5?'½':'1'} bêtise (${p})`);persist();const total=c[p],st=pickState(total);let title=amount===.5?'Petit oups ! 😯':'Oups !',sub=`${c.name} : ${fmt(total)} / ${state.settings.threshold} (${p==='midi'?'midi':'soir'})`;if(total>=3){title='Oh oh… 😈';sub=`3 bêtises : pas de ${state.settings.reward}`}else if(total>=2){title='Attention… 😠';sub=`${fmt(total)} / ${state.settings.threshold} — plus qu’une !`}play(st,title,sub).catch(()=>{})};
  window.good=id=>{const c=state.children.find(x=>x.id===id);if(!c||!isRomane(c))return previousGood?.(id);c.last.push(snapshot(c));c.stars++;addHistory(`${c.name} : ⭐ bonne action`);persist();play('good','Bravo Romane ! ⭐','Super bonne action').catch(()=>{})};
  Object.values(files).forEach(f=>{const i=new Image();i.src=ASSET_BASE+f+'?v=2'});
})();