(()=>{
  const ROMANE_BASE='https://raw.githubusercontent.com/ecopilot-project/Petites-b-tises/main/Asset/Romane/';
  const NORA_PHOTO='./nora-photo-originale.webp';
  const files={zero:'zero.webp',half:'half.webp',one:'one.webp',two:'two.webp',three:'three.webp',good:'good.webp'};
  const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const who=c=>norm(c?.name);
  let overlay=null;
  function ensureOverlay(){if(overlay)return overlay;overlay=document.createElement('div');overlay.id='kidPackOverlay';overlay.innerHTML=`<style>#kidPackOverlay{position:fixed;inset:0;display:none;align-items:center;justify-content:center;z-index:25000;background:rgba(24,42,66,.45);padding:18px}#kidPackOverlay.show{display:flex}#kidPackCard{width:min(92vw,430px);background:white;border-radius:34px;padding:16px;box-shadow:0 30px 90px rgba(0,0,0,.28);text-align:center}#kidPackStage{position:relative;width:100%;aspect-ratio:1;overflow:hidden;border-radius:26px;background:#eef2f7}#kidPackImg{width:100%;height:100%;object-fit:cover;display:block}#kidPackFx{position:absolute;inset:0;pointer-events:none}.kpTag{position:absolute;left:50%;bottom:5%;background:rgba(255,255,255,.95);border-radius:999px;padding:10px 16px;font:900 21px system-ui;color:#17365d}.kpEmoji{position:absolute;filter:drop-shadow(0 6px 8px #0004)}#kidPackTitle{font-size:31px;line-height:1.05;font-weight:950;color:#17365d;margin-top:12px}#kidPackSub{font-size:16px;color:#718096;margin-top:5px}</style><div id="kidPackCard"><div id="kidPackStage"><img id="kidPackImg"><div id="kidPackFx"></div></div><div id="kidPackTitle"></div><div id="kidPackSub"></div></div>`;document.body.appendChild(overlay);return overlay}
  function pickState(total){if(total>=3)return'three';if(total>=2)return'two';if(total>=1)return'one';if(total>=.5)return'half';return'zero'}
  function animate(el,frames,opts){try{return el.animate(frames,opts)}catch{return null}}
  function particle(fx,chars,count=18){for(let i=0;i<count;i++){const s=document.createElement('span');s.textContent=chars[i%chars.length];s.style.position='absolute';s.style.left=(4+Math.random()*90)+'%';s.style.bottom=(-5+Math.random()*20)+'%';s.style.fontSize=(22+Math.random()*12)+'px';fx.appendChild(s);animate(s,[{opacity:0,transform:'translateY(25px) rotate(0) scale(.6)'},{opacity:1,offset:.2},{opacity:0,transform:`translateY(${-190-Math.random()*90}px) rotate(${180+Math.random()*180}deg) scale(1.15)`}],{duration:1100+Math.random()*650,delay:Math.random()*350,easing:'ease-out',fill:'forwards'});setTimeout(()=>s.remove(),2100)}}
  async function playRomane(stateName,title,sub){const o=ensureOverlay(),card=o.querySelector('#kidPackCard'),img=o.querySelector('#kidPackImg'),fx=o.querySelector('#kidPackFx');fx.innerHTML='';o.querySelector('#kidPackTitle').textContent=title;o.querySelector('#kidPackSub').textContent=sub||'';img.src=ROMANE_BASE+files[stateName]+'?v=18';o.classList.add('show');animate(card,[{opacity:0,transform:'scale(.82)'},{opacity:1,transform:'scale(1)'}],{duration:320,easing:'cubic-bezier(.2,.9,.2,1.1)'});await new Promise(r=>setTimeout(r,stateName==='three'?2300:1900));o.classList.remove('show')}
  async function playNora(kind,title,sub){const o=ensureOverlay(),card=o.querySelector('#kidPackCard'),img=o.querySelector('#kidPackImg'),fx=o.querySelector('#kidPackFx');o.querySelector('#kidPackTitle').textContent=title;o.querySelector('#kidPackSub').textContent=sub||'';fx.innerHTML='';img.src=NORA_PHOTO+'?v=18';o.classList.add('show');
    animate(card,[{opacity:0,transform:'translateY(14px) scale(.94)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:340,easing:'cubic-bezier(.2,.9,.2,1.1)'});
    await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
    const warning=kind==='two'||kind==='three';
    animate(img,warning?[{transform:'scale(1.02)'},{transform:'scale(1.07) rotate(-.6deg)',offset:.35},{transform:'scale(1.07) rotate(.6deg)',offset:.7},{transform:'scale(1.04)'}]:[{transform:'scale(1.02)'},{transform:'scale(1.075) translateY(-4px)',offset:.52},{transform:'scale(1.04)'}],{duration:1700,easing:'ease-in-out',fill:'forwards'});
    let tag='';if(kind==='half')tag='Petit oups ! 😯';if(kind==='one')tag='Oh là là… 😬';if(kind==='two')tag='Attention… plus qu’une !';if(kind==='three')tag='Pas de bonbon 😈';if(kind==='good')tag='Bravo Nora ! ⭐';if(kind==='birthday')tag='Joyeux anniversaire Nora ! 🎂';fx.innerHTML=`<div class="kpTag">${tag}</div>`;
    const t=fx.querySelector('.kpTag');animate(t,[{opacity:0,transform:'translate(-50%,28px) scale(.82)'},{opacity:1,transform:'translate(-50%,0) scale(1)'}],{duration:460,delay:120,easing:'cubic-bezier(.2,1,.2,1.2)',fill:'both'});
    const add=(html)=>{fx.insertAdjacentHTML('beforeend',html);const els=[...fx.querySelectorAll('.kpEmoji')];els.forEach((e,i)=>animate(e,[{opacity:0,transform:'translateY(-30px) scale(.25)'},{opacity:1,transform:'translateY(4px) scale(1.18)',offset:.7},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:620,delay:130+i*90,easing:'cubic-bezier(.2,1,.2,1.2)',fill:'both'}))};
    if(kind==='half')add('<span class="kpEmoji" style="right:8%;top:8%;font-size:58px">❗</span>');
    if(kind==='one')add('<span class="kpEmoji" style="left:8%;top:10%;font-size:56px">💭</span>');
    if(kind==='two')add('<span class="kpEmoji" style="left:8%;top:12%;font-size:58px">⚡</span><span class="kpEmoji" style="right:8%;top:15%;font-size:58px">⚡</span>');
    if(kind==='three')add('<span class="kpEmoji" style="left:14%;top:2%;font-size:70px">🔺</span><span class="kpEmoji" style="right:14%;top:2%;font-size:70px">🔺</span>');
    if(kind==='good'){add('<span class="kpEmoji" style="left:8%;top:10%;font-size:56px">⭐</span><span class="kpEmoji" style="right:9%;top:12%;font-size:52px">✨</span>');particle(fx,['⭐','✨','💛'],24)}
    if(kind==='birthday'){add('<span class="kpEmoji" style="left:50%;top:2%;font-size:76px;margin-left:-38px">👑</span>');particle(fx,['🎉','🎈','✨','💗'],30)}
    await new Promise(r=>setTimeout(r,kind==='birthday'?3300:2500));o.classList.remove('show')}
  window.NoraPack={playBirthday:()=>playNora('birthday','Joyeux anniversaire Nora ! 🎂','Aujourd’hui, c’est ta journée 🎉')};
  const previousBad=window.bad,previousGood=window.good;
  window.bad=(id,p,amount=1)=>{const c=state.children.find(x=>x.id===id);if(!c)return previousBad?.(id,p,amount);const n=who(c);if(n!=='romane'&&n!=='nora')return previousBad?.(id,p,amount);c.last.push(snapshot(c));c[p]=Math.min(state.settings.threshold,c[p]+amount);addHistory(`${c.name} : +${amount===.5?'½':'1'} bêtise (${p})`);persist();const total=c[p],st=pickState(total);let title=amount===.5?'Petit oups ! 😯':'Oups !',sub=`${c.name} : ${fmt(total)} / ${state.settings.threshold} (${p==='midi'?'midi':'soir'})`;if(total>=3){title='Oh oh… 😈';sub=`3 bêtises : pas de ${state.settings.reward}`}else if(total>=2){title='Attention… 😠';sub=`${fmt(total)} / ${state.settings.threshold} — plus qu’une !`}if(n==='romane')playRomane(st,title,sub).catch(()=>{});else playNora(st,title,sub).catch(()=>{})};
  window.good=id=>{const c=state.children.find(x=>x.id===id);if(!c)return previousGood?.(id);const n=who(c);if(n!=='romane'&&n!=='nora')return previousGood?.(id);c.last.push(snapshot(c));c.stars++;addHistory(`${c.name} : ⭐ bonne action`);persist();if(n==='romane')playRomane('good','Bravo Romane ! ⭐','Super bonne action').catch(()=>{});else playNora('good','Bravo Nora ! ⭐','Super bonne action').catch(()=>{})};
})();